DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS bid_status;
DROP TYPE IF EXISTS task_status;
DROP TYPE IF EXISTS user_role;